/**
 * Build-time script: fetch models.dev API, filter to the three closed-source
 * provider families we care about, emit a frozen TS snapshot.
 *
 * Run with:  pnpm run sync-models
 *
 * Runtime zero-network: codep only reads the generated file.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const API = "https://models.dev/api.json";
const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "config",
  "generated",
  "models.generated.ts",
);

type ProviderId = "claude" | "codex" | "gemini";

interface RawModel {
  id: string;
  name?: string;
  family?: string;
  reasoning?: boolean;
  tool_call?: boolean;
  attachment?: boolean;
  modalities?: { input?: string[]; output?: string[] };
  cost?: { input?: number; output?: number };
  limit?: { context?: number; output?: number };
  knowledge?: string;
  release_date?: string;
  status?: string;
}

interface RawProvider {
  id: string;
  name: string;
  models: Record<string, RawModel>;
}

interface RawAll {
  [providerId: string]: RawProvider;
}

interface NormalizedModel {
  id: string;
  displayName: string;
  provider: ProviderId;
  family: string;
  reasoning: boolean;
  toolCall: boolean;
  vision: boolean;
  contextWindow: number;
  maxOutput: number;
  costPerMInput: number;
  costPerMOutput: number;
  releaseDate?: string;
  knowledgeCutoff?: string;
}

// Map upstream provider id -> our ProviderId. Only the three official
// first-party endpoints are trusted; aggregators (openrouter, etc.) are
// ignored to keep the snapshot lean and consistent.
const PROVIDER_MAP: Record<string, ProviderId> = {
  anthropic: "claude",
  openai: "codex",
  google: "gemini",
  "google-vertex": "gemini",
};

// Families we care about per provider. Anything else (embeddings, image gen,
// audio, deprecated small models) is dropped.
const FAMILY_ALLOW: Record<ProviderId, RegExp> = {
  claude: /^claude-(opus|sonnet|haiku)/,
  codex: /^(gpt-codex|gpt-pro|gpt-mini|gpt-nano|gpt|o-mini|o-pro|o)$/,
  gemini: /^gemini-(pro|flash|flash-lite)/,
};

function toNormalized(
  provider: ProviderId,
  raw: RawModel,
): NormalizedModel | null {
  if (raw.status === "deprecated") return null;
  const family = raw.family ?? "";
  if (!FAMILY_ALLOW[provider].test(family)) return null;

  const input = raw.modalities?.input ?? ["text"];
  const vision = input.includes("image") || input.includes("pdf");
  const context = raw.limit?.context ?? 0;
  const out = raw.limit?.output ?? 0;
  if (context < 32_000) return null; // drop legacy small-context models

  return {
    id: raw.id,
    displayName: raw.name ?? raw.id,
    provider,
    family,
    reasoning: !!raw.reasoning,
    toolCall: !!raw.tool_call,
    vision,
    contextWindow: context,
    maxOutput: out,
    costPerMInput: raw.cost?.input ?? 0,
    costPerMOutput: raw.cost?.output ?? 0,
    releaseDate: raw.release_date,
    knowledgeCutoff: raw.knowledge,
  };
}

function pickLatestPerFamily(models: NormalizedModel[]): NormalizedModel[] {
  const byKey = new Map<string, NormalizedModel>();
  for (const m of models) {
    const existing = byKey.get(m.family);
    if (!existing) {
      byKey.set(m.family, m);
      continue;
    }
    const a = m.releaseDate ?? "";
    const b = existing.releaseDate ?? "";
    if (a > b) byKey.set(m.family, m);
  }
  return [...byKey.values()].sort((a, b) =>
    a.provider === b.provider
      ? a.family.localeCompare(b.family)
      : a.provider.localeCompare(b.provider),
  );
}

async function main(): Promise<void> {
  process.stdout.write(`Fetching ${API} ...\n`);
  const res = await fetch(API);
  if (!res.ok) throw new Error(`models.dev returned ${res.status}`);
  const data = (await res.json()) as RawAll;

  const all: NormalizedModel[] = [];
  for (const [upId, prov] of Object.entries(data)) {
    const ourId = PROVIDER_MAP[upId];
    if (!ourId) continue;
    for (const raw of Object.values(prov.models)) {
      const n = toNormalized(ourId, raw);
      if (n) all.push(n);
    }
  }

  const picked = pickLatestPerFamily(all);
  process.stdout.write(
    `Selected ${picked.length} model(s) across ${Object.values(PROVIDER_MAP)
      .filter((v, i, a) => a.indexOf(v) === i)
      .join(", ")}.\n`,
  );

  const header = [
    "// AUTO-GENERATED by scripts/sync-models.ts — do not edit by hand.",
    "// Source: https://models.dev/api.json",
    `// Generated: ${new Date().toISOString()}`,
    "",
    'import type { ModelSpec } from "../../router/model-types.js";',
    "",
    "export const MODELS: readonly ModelSpec[] = [",
  ].join("\n");

  const body = picked
    .map(
      (m) =>
        "  " +
        JSON.stringify({
          id: m.id,
          displayName: m.displayName,
          provider: m.provider,
          family: m.family,
          reasoning: m.reasoning,
          toolCall: m.toolCall,
          vision: m.vision,
          contextWindow: m.contextWindow,
          maxOutput: m.maxOutput,
          costPerMInput: m.costPerMInput,
          costPerMOutput: m.costPerMOutput,
          releaseDate: m.releaseDate,
          knowledgeCutoff: m.knowledgeCutoff,
        }) +
        ",",
    )
    .join("\n");

  const footer = "] as const;\n";
  const content = `${header}\n${body}\n${footer}`;

  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, content, "utf8");
  process.stdout.write(`Wrote ${OUT}\n`);
}

main().catch((err) => {
  process.stderr.write(`sync-models failed: ${err.message ?? err}\n`);
  process.exit(1);
});
